#!/usr/bin/env python3

# Copyright © 2015 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import argparse
import sys
import collections

def drop_boring_prefixes(counter):
    for prefix in list(counter.keys()):
        for i in range(0, len(prefix)):
            subprefix = prefix[:i]
            assert prefix != subprefix
            if counter[prefix] == counter[subprefix]:
                del counter[subprefix]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-b', '--ignore-boring', action='store_true')
    options = ap.parse_args()
    counter = collections.Counter()
    for line in sys.stdin:
        line = line.rstrip('\n')
        for i in range(0, len(line) + 1):
            prefix = line[:i]
            counter[prefix] += 1
    if options.ignore_boring:
        drop_boring_prefixes(counter)
    for prefix, i in sorted(counter.items()):
        print('{i:7}\t{s}'.format(i=i, s=prefix))

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
